### ISSUE TITLE
npm run dev issue

### ISSUE THREAD

**Issue by codingcaffeine** [omar-dulaimi/create-trpc-app#1]
### Bug description

`''wait-on' is not recognized as an internal or external command,`
after running `npm run dev`

### tRPC information

╰─ npm run dev

> express-server@9.23.2 dev
> run-p dev:* --print-label

[dev:server]
[dev:server] > express-server@9.23.2 dev:server
[dev:server] > nodemon -e ts -w . -x ts-node ./src/server
[dev:server]
[dev:client]
[dev:client] > express-server@9.23.2 dev:client
[dev:client] > nodemon -e ts -w . -x 'wait-on tcp:2021 && ts-node ./src/client'
[dev:client]
[dev:client] [nodemon] 2.0.19
[dev:client] [nodemon] to restart at any time, enter `rs`
[dev:server] [nodemon] 2.0.19
[dev:client] [nodemon] watching path(s): *.*
[dev:client] [nodemon] watching extensions: ts
[dev:server] [nodemon] to restart at any time, enter `rs`
[dev:client] [nodemon] starting `'wait-on tcp:2021`
[dev:server] [nodemon] watching path(s): *.*
[dev:server] [nodemon] watching extensions: ts
[dev:server] [nodemon] starting `ts-node ./src/server.ts`
[dev:client] ''wait-on' is not recognized as an internal or external command,
[dev:client] operable program or batch file.
[dev:client] [nodemon] app crashed - waiting for file changes before starting...
[dev:server] listening on port 2021

### Environment & setup

- OS: Windows
- Database: SQLite
- Node.js version: v16

### tRPC Version

```
"@trpc/client": "^9.23.2",
"@trpc/server": "^9.23.2"
```

**Comment by omar-dulaimi** [comment]
@codingcaffeine Please fill the `Environment & setup` section so I could understand your case better.

**Comment by daniellaera** [comment]
same problem as @codingcaffeine , same environment

**Comment by omar-dulaimi** [comment]
@codingcaffeine @daniellaera Guys unfortunately, I do not have a windows machine to test any solutions on.
So if you would like, please give it a try.

**Comment by codingcaffeine** [comment]
![issue](https://user-images.githubusercontent.com/87785221/180641335-9df382a1-33a6-4f10-b022-435bfc00f0dd.png)

on windows

**Comment by omar-dulaimi** [comment]
@codingcaffeine Out of curiosity, which example did you download?
What command did you execute?

**Comment by codingcaffeine** [comment]
`npx create-trpc-appx@latest`
that creates me a repo and then I run `npm run dev`

**Comment by omar-dulaimi** [comment]
@codingcaffeine 
The default template is equivalent to `npx create-trpc-appx --example express-server`

You can find that example here: https://github.com/trpc/trpc/tree/main/examples/express-server


I think you should open an issue there.

**Comment by codingcaffeine** [comment]
Indeed, thanks

**Comment by omar-dulaimi** [comment]
Did you try that example locally too, and it did not work?
Because `wait-on` should work cross env as mentioned on its README.

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/create-trpc-app/releases/tag/0.0.1
