### ISSUE TITLE
No longer compiles after app creation

### ISSUE THREAD

**Issue by mredbishop** [omar-dulaimi/create-trpc-app#4]
### Bug description

After running this to create a new blank app with no params the app does not compile due to a type error with the router object type.

### How to reproduce

1. Create an app with **_yarn create trpc-appx_**
2. Open compile the app.
3. See compilation error.

### Expected behavior

The app compiles and starts with **_yarn dev_**

### tRPC information

There is no additional info, it doesn't compile 
![image](https://github.com/omar-dulaimi/create-trpc-app/assets/1096293/20c22bed-4e22-41f1-84e1-89b6133f0d30)

### Environment & setup

OS: Ubuntu 23.04
Database: None
Node.js version: 16

### tRPC Version

latest I assume?

**Comment by omar-dulaimi** [comment]
Should be fixed with latest version 0.0.2

Thank you for reporting the issue
